CREATE TYPE reservation_status AS ENUM ('PENDING','AUTHORIZED','EXECUTING','COMMITTED','RELEASED','EXPIRED','FAILED');
CREATE TYPE payment_attempt_status AS ENUM ('NOT_STARTED','ORDER_CREATING','ORDER_CREATED','CAPTURE_PENDING','CAPTURED','FAILED','CANCELLED');

CREATE TABLE principals (id text PRIMARY KEY, display_name text NOT NULL CHECK (length(display_name)>0), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE agent_passports (id text PRIMARY KEY, principal_id text NOT NULL REFERENCES principals(id), display_name text NOT NULL, issued_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, status text NOT NULL CHECK(status IN ('ACTIVE','SUSPENDED','REVOKED')), capabilities jsonb NOT NULL, CHECK(expires_at>issued_at));
CREATE TABLE mandates (id text PRIMARY KEY, principal_id text NOT NULL REFERENCES principals(id), authorized_agent_id text NOT NULL REFERENCES agent_passports(id), fingerprint char(64) NOT NULL, document jsonb NOT NULL, nonce text NOT NULL, cumulative_limit_minor bigint, spent_minor bigint NOT NULL DEFAULT 0 CHECK(spent_minor>=0), created_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, UNIQUE(id,nonce), CHECK(cumulative_limit_minor IS NULL OR cumulative_limit_minor>0), CHECK(expires_at>created_at));
CREATE TABLE transaction_proposals (id text PRIMARY KEY, mandate_id text NOT NULL REFERENCES mandates(id), agent_id text NOT NULL REFERENCES agent_passports(id), nonce text NOT NULL, amount_minor bigint NOT NULL CHECK(amount_minor>=0), currency char(3) NOT NULL CHECK(currency ~ '^[A-Z]{3}$'), document jsonb NOT NULL, proposed_at timestamptz NOT NULL, UNIQUE(mandate_id,nonce));
CREATE TABLE decision_receipts (id text PRIMARY KEY, proposal_id text NOT NULL UNIQUE REFERENCES transaction_proposals(id), mandate_id text NOT NULL REFERENCES mandates(id), agent_id text NOT NULL REFERENCES agent_passports(id), decision text NOT NULL CHECK(decision IN ('ALLOW','DENY','ESCALATE')), document jsonb NOT NULL, evaluated_at timestamptz NOT NULL);
CREATE TABLE approvals (id text PRIMARY KEY, receipt_id text NOT NULL UNIQUE REFERENCES decision_receipts(id), proposal_id text NOT NULL REFERENCES transaction_proposals(id), principal_id text NOT NULL REFERENCES principals(id), status text NOT NULL DEFAULT 'APPROVED' CHECK(status IN ('APPROVED','REVOKED','EXPIRED')), approved_at timestamptz NOT NULL);
CREATE TABLE replay_keys (scope text NOT NULL, replay_key text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(scope,replay_key));
CREATE TABLE authorization_reservations (id text PRIMARY KEY, mandate_id text NOT NULL REFERENCES mandates(id), proposal_id text NOT NULL UNIQUE REFERENCES transaction_proposals(id), receipt_id text NOT NULL UNIQUE REFERENCES decision_receipts(id), amount_minor bigint NOT NULL CHECK(amount_minor>0), currency char(3) NOT NULL CHECK(currency ~ '^[A-Z]{3}$'), status reservation_status NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE payment_attempts (id text PRIMARY KEY, reservation_id text NOT NULL REFERENCES authorization_reservations(id), provider text NOT NULL, idempotency_key text NOT NULL UNIQUE, provider_order_id text UNIQUE, provider_status text, status payment_attempt_status NOT NULL DEFAULT 'NOT_STARTED', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE evidence_events (sequence bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, id text NOT NULL UNIQUE, type text NOT NULL, occurred_at timestamptz NOT NULL, data jsonb NOT NULL, previous_hash char(64), hash char(64) NOT NULL UNIQUE, CHECK((sequence=1 AND previous_hash IS NULL) OR sequence>1));
